[workspace]
resolver = "2"

members = [
  "cli-pdf-to-text",
  "cli-epub-to-text",
  "cli-justify",
  "cli-text-reader",
  "rustic-reader",

  # Internal
  # "examples",
]

[workspace.lints.rust]
unused_parens = "allow"

[workspace.lints.clippy]
needless_return = "allow"
